name: infoedomex
description: A new Flutter project.

publish_to: 'none' # 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  #firebase database
  cloud_firestore: ^0.14.1+2
  firebase_storage: ^4.0.1
  firebase_database: ^4.1.1
  
  #firebase auth 
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2

  #intl: Servicios de Internacionalizacion
  intl: ^0.16.1
  
  #image_picker: Libreria para tomar fotos desde la galeria
  image_picker: ^0.6.7+11

  #Alerts
  rflutter_alert: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
